openapi: 3.0.1
info:
  title: API bundler cadastre
  version: "1.404"
servers:
  - url: https://cadastre.data.gouv.fr/bundler
paths:
  /pci-vecteur/departements/{codeDepartement}/{format}:
    get:
      tags: [PCI Vecteur]
      parameters:
        - $ref: '#/components/parameters/codeDepartement'
        - $ref: '#/components/parameters/formatPciVecteur'
      responses:
        $ref: '#/components/responses/Download'
  /pci-vecteur/feuilles/{codeFeuille}/{format}:
    get:
      tags: [PCI Vecteur]
      parameters:
        - $ref: '#/components/parameters/codeFeuille'
        - $ref: '#/components/parameters/formatPciVecteur'
      responses:
        $ref: '#/components/responses/Download'
  /pci-vecteur/communes/{codeCommune}/{format}:
    get:
      tags: [PCI Vecteur]
      parameters:
        - $ref: '#/components/parameters/codeCommune'
        - $ref: '#/components/parameters/formatPciVecteur'
      responses:
        $ref: '#/components/responses/Download'
  /pci-vecteur/communes:
    get:
      tags: [PCI Vecteur]
      parameters:
        - $ref: '#/components/parameters/formatPciVecteurQuery'
        - $ref: '#/components/parameters/inseeCodes'
      responses:
        $ref: '#/components/responses/Download'
  /pci-vecteur/epcis/{codeEPCI}/{format}:
    get:
      tags: [PCI Vecteur]
      parameters:
        - $ref: '#/components/parameters/codeEPCI'
        - $ref: '#/components/parameters/formatPciVecteur'
      responses:
        $ref: '#/components/responses/Download'
  /pci-image/communes/{codeCommune}/tiff:
    get:
      tags: [PCI Image]
      parameters:
        - $ref: '#/components/parameters/codeCommune'
      responses:
        $ref: '#/components/responses/Download'
  /pci-image/epcis/{codeEPCI}/tiff:
    get:
      tags: [PCI Image]
      parameters:
        - $ref: '#/components/parameters/codeEPCI'
      responses:
        $ref: '#/components/responses/Download'
  /cadastre-etalab/departements/{codeDepartement}/shp/{layer}:
    get:
      tags: [Cadastre Etalab]
      parameters:
        - $ref: '#/components/parameters/codeDepartement'
        - $ref: '#/components/parameters/layerType'
      responses:
        $ref: '#/components/responses/Download'
  /cadastre-etalab/departements/{codeDepartement}/{format}/{layer}:
    get:
      tags: [Cadastre Etalab]
      parameters:
        - $ref: '#/components/parameters/codeDepartement'
        - $ref: '#/components/parameters/formatEtalabCadastre'
        - $ref: '#/components/parameters/layerType'
      responses:
        $ref: '#/components/responses/Download'
  /cadastre-etalab/communes/{codeCommune}/shp/{layer}:
    get:
      tags: [Cadastre Etalab]
      parameters:
        - $ref: '#/components/parameters/codeCommune'
        - $ref: '#/components/parameters/layerType'
      responses:
        $ref: '#/components/responses/Download'
  /cadastre-etalab/communes/{codeCommune}/{format}/{layer}:
    get:
      tags: [Cadastre Etalab]
      parameters:
        - $ref: '#/components/parameters/codeCommune'
        - $ref: '#/components/parameters/formatEtalabCadastre'
        - $ref: '#/components/parameters/layerType'
      responses:
        $ref: '#/components/responses/Download'
  /cadastre-etalab/epcis/{codeEPCI}/shp/{layer}:
    get:
      tags: [Cadastre Etalab]
      parameters:
        - $ref: '#/components/parameters/codeEPCI'
        - $ref: '#/components/parameters/layerType'
      responses:
        $ref: '#/components/responses/Download'
  /cadastre-etalab/epcis/{codeEPCI}/{format}/{layer}:
    get:
      tags: [Cadastre Etalab]
      parameters:
        - $ref: '#/components/parameters/codeEPCI'
        - $ref: '#/components/parameters/formatEtalabCadastre'
        - $ref: '#/components/parameters/layerType'
      responses:
        $ref: '#/components/responses/Download'
  /{millesime}/pci-vecteur/departements/{codeDepartement}/{format}:
    get:
      tags: [PCI Vecteur]
      parameters:
        - $ref: '#/components/parameters/millesime'
        - $ref: '#/components/parameters/codeDepartement'
        - $ref: '#/components/parameters/formatPciVecteur'
      responses:
        $ref: '#/components/responses/Download'
  /{millesime}/pci-vecteur/feuilles/{codeFeuille}/{format}:
    get:
      tags: [PCI Vecteur]
      parameters:
        - $ref: '#/components/parameters/millesime'
        - $ref: '#/components/parameters/codeFeuille'
        - $ref: '#/components/parameters/formatPciVecteur'
      responses:
        $ref: '#/components/responses/Download'
  /{millesime}/pci-vecteur/communes/{codeCommune}/{format}:
    get:
      tags: [PCI Vecteur]
      parameters:
        - $ref: '#/components/parameters/millesime'
        - $ref: '#/components/parameters/codeCommune'
        - $ref: '#/components/parameters/formatPciVecteur'
      responses:
        $ref: '#/components/responses/Download'
  /{millesime}/pci-vecteur/communes:
    get:
      tags: [PCI Vecteur]
      parameters:
        - $ref: '#/components/parameters/millesime'
        - $ref: '#/components/parameters/formatPciVecteurQuery'
        - $ref: '#/components/parameters/inseeCodes'
      responses:
        $ref: '#/components/responses/Download'
  /{millesime}/pci-vecteur/epcis/{codeEPCI}/{format}:
    get:
      tags: [PCI Vecteur]
      parameters:
        - $ref: '#/components/parameters/millesime'
        - $ref: '#/components/parameters/codeEPCI'
        - $ref: '#/components/parameters/formatPciVecteur'
      responses:
        $ref: '#/components/responses/Download'
  /{millesime}/pci-image/communes/{codeCommune}/tiff:
    get:
      tags: [PCI Image]
      parameters:
        - $ref: '#/components/parameters/millesime'
        - $ref: '#/components/parameters/codeCommune'
      responses:
        $ref: '#/components/responses/Download'
  /{millesime}/pci-image/epcis/{codeEPCI}/tiff:
    get:
      tags: [PCI Image]
      parameters:
        - $ref: '#/components/parameters/millesime'
        - $ref: '#/components/parameters/codeEPCI'
      responses:
        $ref: '#/components/responses/Download'
  /{millesime}/cadastre-etalab/departements/{codeDepartement}/shp/{layer}:
    get:
      tags: [Cadastre Etalab]
      parameters:
        - $ref: '#/components/parameters/millesime'
        - $ref: '#/components/parameters/codeDepartement'
        - $ref: '#/components/parameters/layerType'
      responses:
        $ref: '#/components/responses/Download'
  /{millesime}/cadastre-etalab/departements/{codeDepartement}/{format}/{layer}:
    get:
      tags: [Cadastre Etalab]
      parameters:
        - $ref: '#/components/parameters/millesime'
        - $ref: '#/components/parameters/codeDepartement'
        - $ref: '#/components/parameters/formatEtalabCadastre'
        - $ref: '#/components/parameters/layerType'
      responses:
        $ref: '#/components/responses/Download'
  /{millesime}/cadastre-etalab/communes/{codeCommune}/shp/{layer}:
    get:
      tags: [Cadastre Etalab]
      parameters:
        - $ref: '#/components/parameters/millesime'
        - $ref: '#/components/parameters/codeCommune'
        - $ref: '#/components/parameters/layerType'
      responses:
        $ref: '#/components/responses/Download'
  /{millesime}/cadastre-etalab/communes/{codeCommune}/{format}/{layer}:
    get:
      tags: [Cadastre Etalab]
      parameters:
        - $ref: '#/components/parameters/millesime'
        - $ref: '#/components/parameters/codeCommune'
        - $ref: '#/components/parameters/formatEtalabCadastre'
        - $ref: '#/components/parameters/layerType'
      responses:
        $ref: '#/components/responses/Download'
  /{millesime}/cadastre-etalab/epcis/{codeEPCI}/shp/{layer}:
    get:
      tags: [Cadastre Etalab]
      parameters:
        - $ref: '#/components/parameters/millesime'
        - $ref: '#/components/parameters/codeEPCI'
        - $ref: '#/components/parameters/layerType'
      responses:
        $ref: '#/components/responses/Download'
  /{millesime}/cadastre-etalab/epcis/{codeEPCI}/{format}/{layer}:
    get:
      tags: [Cadastre Etalab]
      parameters:
        - $ref: '#/components/parameters/millesime'
        - $ref: '#/components/parameters/codeEPCI'
        - $ref: '#/components/parameters/formatEtalabCadastre'
        - $ref: '#/components/parameters/layerType'
      responses:
        $ref: '#/components/responses/Download'
components:
  responses:
    Download:
      '200':
        description: ZIP
        content:
          application/zip:
            schema:
              type: string
              format: binary
      '404':
        description: Erreur
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Error'
  schemas:
    Error:
      type: object
      properties:
        code:
          type: integer
        message:
          type: string
  parameters:
    millesime:
      name: millesime
      in: path
      required: true
      description: Date du millésime
      schema:
        type: string
        pattern: '^\d{4}-\d{2}-\d{2}$'
    formatEtalabCadastre:
      name: format
      in: path
      required: true
      schema:
        type: string
        enum: [geojson, geojson-gz, shp]
    formatPciVecteur:
      name: format
      in: path
      required: true
      schema:
        type: string
        enum: [edigeo, edigeo-cc, dxf, dxf-cc]
    formatPciVecteurQuery:
      name: format
      in: query
      required: true
      schema:
        type: string
        enum: [edigeo, edigeo-cc, dxf, dxf-cc]
    layerType:
      name: layer
      in: path
      required: true
      schema:
        type: string
        enum:
          - batiments
          - communes
          - feuilles
          - parcelles
          - sections
          - lieux_dits
          - subdivisions_fiscales
          - prefixes_sections
    inseeCodes:
      name: insee_codes
      in: query
      required: true
      style: form
      explode: false
      schema:
        type: array
        items:
          type: string
        minItems: 1
        maxItems: 300
    codeDepartement:
      name: codeDepartement
      in: path
      required: true
      schema:
        type: string
    codeFeuille:
      name: codeFeuille
      in: path
      required: true
      schema:
        type: string
    codeCommune:
      name: codeCommune
      in: path
      required: true
      schema:
        type: string
    codeEPCI:
      name: codeEPCI
      in: path
      required: true
      schema:
        type: string
